//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Domain.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Connection_String_Is_Empty {
            get {
                return ResourceManager.GetString("Connection_String_Is_Empty", resourceCulture);
            }
        }
        
        public static string Exiting_Application {
            get {
                return ResourceManager.GetString("Exiting_Application", resourceCulture);
            }
        }
        
        public static string Id_Can_Not_Be_Non_Positive_Number {
            get {
                return ResourceManager.GetString("Id_Can_Not_Be_Non_Positive_Number", resourceCulture);
            }
        }
        
        public static string Name_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Name_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        public static string Value_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Value_Can_Not_Be_Empty", resourceCulture);
            }
        }
    }
}
